### ISSUE TITLE
Update DB using AJAX - Button on Bootstrap Modal

### ISSUE THREAD

**Issue by decoded-cipher** [decoded-cipher/freshers-day#2]
The following Buttons on Popup Modal don't work.

### Button - Task Pending
- Must Close the Modal
- Indicate the pending/ongoing tasks from others.
  - **Note** : Update the status value to 1 or 2.
### Button - Task Completed
- Must Close the Modal
- Remove the bubble from the list
  - **Note** : Update the status value to 2 or 1
 
![image](https://user-images.githubusercontent.com/44474792/146918836-00a0af6c-09c0-41cb-8242-3107bde9bfc6.png)

**Comment by Dlewis89** [comment]
Is this issue still in need of a resolution?

**Comment by decoded-cipher** [comment]
Yup. Actually, I haven't looked into this project for quite some time... It'll be great if you could fix the pending issues and if anything that emerges meanwhile...

**Comment by Dlewis89** [comment]
@decoded-cipher no problem, ill starting looking into it and let you know if i have any questions.

**Comment by Dlewis89** [comment]
Also, do you have an image that you want to use for pending task or do you want to have like a bubble indicator some where around the image to show it's pending status?
