### ISSUE TITLE
Display indicator for Pending Task (Image + Bubble)

### ISSUE THREAD

**Issue by decoded-cipher** [decoded-cipher/freshers-day#4]
_Originally posted by @Dlewis89 in https://github.com/decoded-cipher/freshers-day/issues/2#issuecomment-1162234171_

---
Pending Tasks must not disappear till they are marked as complete. To be recognized as easily, tasks could have a different thumbnail. A bubble indicator is also a great suggestion. 

---
@Dlewis89 Since this project is maintained as open-source, I think it'll be great if we could provide both features.

**Comment by Dlewis89** [comment]
Hey, I have finished the bubble indicator and pending task remaining displayed until completed.  I do have two questions.

1. Is there any specific reason why the image paths are being retrieved from the database? If you want to use a different image for pending task and the path needs to be retrieved from the database, it would be easier to redesign the database schema to properly do this or we can use a pending-status CSS class and just swap the class on the element as needed when status is updated.

2. Is it possible for me to get the original images for the project. I'm currently working with a dummy image, and position of the bubble indicator may not be correct if the original images are a different size.

**Comment by decoded-cipher** [comment]
@Dlewis89 Images other than those of the students _(those within the Modal Popup)_ need not be retrieved from DB. Thumbnail Images can be hardcoded. But the pics of students must be retrieved from DB.

---
### Note:
How about using the blue dummy image as the default thumbnail & red one for pending. **The pics used in this project will always be square**.

![pending](https://user-images.githubusercontent.com/44474792/174940403-e988c1ad-efb9-4dee-80ac-58c11276cd2a.png)
![default](https://user-images.githubusercontent.com/44474792/174940623-80334798-3dba-4cba-b0e6-b0c6d1537d6e.png)
